//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataUsuarios.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intermedio
    {
        public int Id { get; set; }
        public int ContactoId { get; set; }
        public int MediosDeContactoId { get; set; }
        public string informacion { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual MediosDeContacto MediosDeContacto { get; set; }
    }
}
